name = "CRM-CFP"
authors = ["Reza Arefidamghani", "Roger Behling", "Yunier Bello-Cruz", "Alfredo N. Iusem", "Luiz-Rafael Santos"]

[deps]
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
BenchmarkProfiles = "ecbce9bc-3e5e-569d-9e29-55181f61f8d0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MKLSparse = "0c723cd3-b8cd-5d40-b370-ba682dde9aae"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
QRMumps = "422b30a1-cc69-4d85-abe7-cc07b540c444"
ThreadedSparseArrays = "59d54670-b8ac-4d81-ab7a-bb56233e17ab"

[compat]
julia = "1.8"
